anchor_version = "0.22.1"
solana_version = "1.9.12"

[scripts]
test = "yarn mocha"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[[test.genesis]]
address = "QMWoBmAyJLAsA1Lh9ugMTw2gciTihncciphzdNzdZYV"
program = "./artifacts/deploy/quarry_mint_wrapper.so"

[[test.genesis]]
address = "QMNeHCGYnLVDn1icRAfQZpjPLBNkfGbSKRB83G5d8KB"
program = "./artifacts/deploy/quarry_mine.so"

[[test.genesis]]
address = "QoP6NfrQbaGnccXQrMLUkog2tQZ4C1RFgJcwDnT8Kmz"
program = "./artifacts/deploy/quarry_operator.so"

[[test.genesis]]
address = "Govz1VyoyLD5BL6CSCxUJLVLsQHRwjfFj1prNsdNg5Jw"
program = "./artifacts/deploy/govern.so"

[[test.genesis]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"
program = "./artifacts/deploy/locked_voter.so"

[[test.genesis]]
address = "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH"
program = "./artifacts/deploy/smart_wallet.so"

[programs.localnet]
gauge = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"

[programs.devnet]
gauge = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"

[programs.testnet]
gauge = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"

[programs.mainnet]
gauge = "GaugesLJrnVjNNWLReiw3Q7xQhycSBRgeHGTMDUaX231"
